### ISSUE TITLE
cannot delete default app

### ISSUE THREAD

**Issue by viktoriasee** [mclear/OMNI-Ring#4]
While I succeed in compiling uploading and testing this demo applet, I fail to delete neither the default app nor the newly created applet.
`$ ./gp --uninstall D276000085
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
Could not read CAP: D276000085 (Das System kann die angegebene Datei nicht finden)`

Can you give a hint?

**Comment by laurimihkels** [comment]
Can you try to use `--delete` command instead of uninstall? 
Like this:
`$ ./gp --delete D276000085`

**Comment by viktoriasee** [comment]
This works, no idea why.

**Comment by laurimihkels** [comment]
I made the change in guide as well.
