### ISSUE TITLE
Please provide source code for factory applet on OMNI ring

### ISSUE THREAD

**Issue by SaulMoonves** [mclear/OMNI-Ring#8]
Would be nice to have.

**Comment by darconeous** [comment]
The small NDEF Applet with the link to their website?

**Comment by benbenbenbenbenben** [comment]
I believe it's from this project: https://github.com/OpenJavaCard/openjavacard-ndef

**Comment by SaulMoonves** [comment]
Alright, I will study that code, thank you.

**Comment by laurimihkels** [comment]
Hi @SaulMoonves,

As @benbenbenbenbenben pointed out the applet on the ring is indeed from https://github.com/OpenJavaCard/openjavacard-ndef. We used the tiny variant with static data set during applet install.

**Comment by SaulMoonves** [comment]
Perfect, this is just the information I need. I've managed to make custom block of NDEF code to to launch urls to write to Mifare passive NFC cards so I think I know what to put on the tiny applet.
